### ISSUE TITLE
Does not appear to work with lein uberjar

### ISSUE THREAD

**Issue by AlainPicard-at-gocatch** [cvillecsteele/lein-git-version#7]
It seems to work fine when I do a lein jar, 
but when I do lein uberjar, I get a stack trace as follows:

gows % lein uberjar
Exception in thread "main" java.io.FileNotFoundException: /Users/ap/Desktop/Dev/gows/src/gows/version.clj (No such file or directory), compiling:(/private/var/folders/2k/lh6ztvq94152dhbkgbl293hm0000gq/T/form-init4190422107294763219.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: /Users/ap/Desktop/Dev/gows/src/gows/version.clj (No such file or directory)

So it looks like it did not produce the desired version.clj file?

--alain picard

**Comment by joekiller** [comment]
This seems to work now and can probably be closed.
